# docker-compose.yml
services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  discord-bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    # --- ZMIANA: Dodajemy mapowanie wolumenów dla klucza ---
    volumes:
      - ./keys:/keys
    depends_on:
      - qdrant

volumes:
  qdrant_data:
