# .github/workflows/sync.yml
name: Sync Knowledge Base to Qdrant

on:
  push:
    branches:
      - main
    paths:
      - 'it/**'
      - 'marketing/**'
      - 'projekty/**'
      - '.knowledge_manifest.yml'
  workflow_dispatch:

jobs:
  sync-data:
    runs-on: ubuntu-latest
    steps:
      # KROK 1: Pobierz zawartość TEGO repozytorium (z wiedzą)
      - name: 1. Checkout Knowledge Base repository
        uses: actions/checkout@v4

      # KROK 2: Ustawienie Pythona (robimy to wcześniej)
      - name: 2. Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # KROK 3: Pobierz TYLKO niezbędne pliki z repozytorium bota
      # To jest implementacja Twojego pomysłu - "sparse checkout".
      - name: 3. Sparse checkout sync script from Bot repository
        run: |
          # Tworzymy folder na kod bota
          mkdir skryba-bot-code
          cd skryba-bot-code

          # Inicjalizujemy puste repozytorium Git
          git init
          git remote add origin https://github.com/Wiecek-K/discord-skryba-bot.git

          # Włączamy tryb sparse-checkout, który pozwala pobierać tylko wybrane foldery
          git config core.sparseCheckout true

          # Definiujemy, które DOKŁADNIE pliki/foldery chcemy pobrać.
          # Potrzebujemy skryptu ORAZ pliku z jego zależnościami.
          echo "bot/scripts/" >> .git/info/sparse-checkout
          echo "requirements.txt" >> .git/info/sparse-checkout

          # Pobieramy tylko gałąź 'main' i tylko zdefiniowane wyżej pliki
          git pull --depth=1 origin main
        
      # KROK 4: Zainstaluj zależności z pobranego pliku requirements.txt
      - name: 4. Install Python dependencies from bot repo
        run: pip install -r skryba-bot-code/requirements.txt

      # KROK 5: Uruchom skrypt synchronizujący
      - name: 5. Run the sync script from bot repo
        run: python skryba-bot-code/bot/scripts/sync_to_qdrant.py
        env:
          QDRANT_HOST: ${{ secrets.QDRANT_HOST_IP }}
          QDRANT_PORT: 6333
