name: Sync Knowledge Base to ChromaDB

on:
  push:
    branches:
      - main  # Uruchom tylko po mergu/pushu do gałęzi 'main'
  workflow_dispatch: # Umożliwia ręczne uruchomienie z interfejsu GitHub

jobs:
  sync-data:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout repository code
        uses: actions/checkout@v4

      - name: 2. Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Cache Sentence Transformers model
        uses: actions/cache@v4
        with:
          path: ~/.cache/torch/sentence_transformers
          key: ${{ runner.os }}-st-cache-${{ hashFiles('**/requirements.txt') }}

      - name: 4. Install Python dependencies
        run: pip install -r requirements.txt

      - name: 5. Run the sync script
        run: python bot/scripts/sync_to_chroma.py
        env:
          CHROMA_HOST: ${{ secrets.CHROMA_HOST_IP }} # Ważne! Używamy sekretu
